name: bookingsolution

services:

  booking.backoffice:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Application/BookingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=backoffice

  booking.middleoffice:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Application/BookingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=middleoffice
      