name: bookingsolution

services:

  booking.admin:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Application/BookingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production-Admin

  booking.planning:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Application/BookingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production-Planning

  booking.sales:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Application/BookingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production-Sales

  booking.support:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Application/BookingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production-Support
