global using System.Globalization;
global using BookingKata.Infrastructure.Common;
global using BookingKata.Sales;
global using BookingKata.Services;
global using Business.Common;
global using VinZ.Common;
global using VinZ.GeoIndexing;
global using VinZ.MessageQueue;
global using static VinZ.MessageQueue.Const;
global using static BookingKata.Infrastructure.Common.Const;