@CQRSBookingKata.API_HostAddress = http://localhost:5291

GET {{CQRSBookingKata.API_HostAddress}}/admin/employees
Accept: application/json

###

GET {{CQRSBookingKata.API_HostAddress}}/admin/hotels
Accept: application/json

###
